In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-06-trees/CreditScoring.csv'

In [3]:
!wget $data -O course-trees_06_CreditScoring.csv

--2026-10-25 11:59:02--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-06-trees/CreditScoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182489 (178K) [text/plain]
Saving to: ‘course-trees_06_CreditScoring.csv’

course-trees_06_Cre 100%[===================>] 178.21K  --.-KB/s    in 0.002s

2026-10-25 11:59:02 (76.7 MB/s) - ‘course-trees_06_CreditScoring.csv’ saved [182489/182489]

In [8]:
!head course-trees_06_CreditScoring.csv

"Status","Seniority","Home","Time","Age","Marital","Records","Job","Expenses","Income","Assets","Debt","Amount","Price"
1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
1,0,1,36,26,1,1,1,46,107,0,0,310,910
1,1,2,60,36,2,1,1,75,214,3500,0,650,1645
1,29,2,60,44,2,1,1,75,125,10000,0,1600,1800
1,9,5,12,27,1,1,1,35,80,0,0,200,1093
1,0,2,60,32,2,1,3,90,107,15000,0,1200,1957

In [9]:
df = pd.read_csv(data)

In [10]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [11]:
df.columns = df.columns.str.lower()

In [12]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [13]:
df.status.value_counts()

status
1    3200
2    1254
0       1
Name: count, dtype: int64

In [14]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

df.status = df.status.map(status_values)

In [15]:
home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

df.home = df.home.map(home_values)

marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

df.marital = df.marital.map(marital_values)

records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

df.records = df.records.map(records_values)

job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

df.job = df.job.map(job_values)

In [16]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [19]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [20]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [21]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4421.0,4408.0,4437.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,131.0,5403.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11573.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

In [22]:
df = df[df.status != 'unk'].reset_index(drop=True)

In [23]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=11)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=11)

In [24]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [25]:
y_train = (df_train.status == 'default').astype('int').values
y_val = (df_val.status == 'default').astype('int').values
y_test = (df_test.status == 'default').astype('int').values

In [26]:
df_train.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,default,10,owner,36,36,married,no,freelance,75,0.0,10000.0,0.0,1000,1400
1,default,6,parents,48,32,single,yes,fixed,35,85.0,0.0,0.0,1100,1330
2,ok,1,parents,48,40,married,no,fixed,75,121.0,0.0,0.0,1320,1600
3,default,1,parents,48,23,single,no,partime,35,72.0,0.0,0.0,1078,1079
4,ok,5,owner,36,46,married,no,freelance,60,100.0,4000.0,0.0,1100,1897

In [30]:
pd.Series(y_train).value_counts()

0    1940
1     732
Name: count, dtype: int64

In [31]:
del df_train['status']
del df_val['status']
del df_test['status']

In [32]:
def assess_risk(client):
    if client['records'] == 'yes':
        if client['job'] == 'parttime':
            return 'default'
        else:
            return 'ok'
    else:
        if client['assets'] > 6000:
            return 'ok'
        else:
            return 'default'

In [33]:
xi = df_train.iloc[0].to_dict()

In [34]:
xi

{'seniority': 10,
 'home': 'owner',
 'time': 36,
 'age': 36,
 'marital': 'married',
 'records': 'no',
 'job': 'freelance',
 'expenses': 75,
 'income': 0.0,
 'assets': 10000.0,
 'debt': 0.0,
 'amount': 1000,
 'price': 1400}

In [35]:
assess_risk(xi)

'ok'

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text

In [37]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

In [38]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [39]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [41]:
y_pred = dt.predict_proba(X_val)[:, 1]
roc_auc_score(y_val, y_pred)

0.6400698699474462

In [42]:
y_pred = dt.predict_proba(X_train)[:, 1]
roc_auc_score(y_train, y_pred)

1.0

In [45]:
dt = DecisionTreeClassifier(max_depth=3)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [46]:
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train:', auc)

y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('val:', auc)

train: 0.7761016984958594
val: 0.7389079944782155

In [47]:
print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- records=yes <= 0.50
|   |--- job=partime <= 0.50
|   |   |--- income <= 74.50
|   |   |   |--- class: 0
|   |   |--- income >  74.50
|   |   |   |--- class: 0
|   |--- job=partime >  0.50
|   |   |--- assets <= 8750.00
|   |   |   |--- class: 1
|   |   |--- assets >  8750.00
|   |   |   |--- class: 0
|--- records=yes >  0.50
|   |--- seniority <= 6.50
|   |   |--- amount <= 862.50
|   |   |   |--- class: 0
|   |   |--- amount >  862.50
|   |   |   |--- class: 1
|   |--- seniority >  6.50
|   |   |--- income <= 103.50
|   |   |   |--- class: 1
|   |   |--- income >  103.50
|   |   |   |--- class: 0

In [48]:
data = [
    [8000, 'default'],
    [2000, 'default'],
    [   0, 'default'],
    [5000, 'ok'],
    [5000, 'ok'],
    [4000, 'ok'],
    [9000, 'ok'],
    [3000, 'default'],
]

df_example = pd.DataFrame(data, columns=['assets', 'status'])
df_example

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

In [49]:
#condition: assets > T ...... question: what is the best T??

In [50]:
#splitting df example into two: df_right where assets > t, and df_left where assets < T

In [51]:
df_example.sort_values('assets')

   assets   status
2       0  default
1    2000  default
7    3000  default
5    4000       ok
4    5000       ok
3    5000       ok
0    8000  default
6    9000       ok

In [52]:
Ts = [0, 2000, 3000, 4000, 5000, 8000]

In [53]:
from IPython.display import display

In [54]:
for T in Ts:
    print(T)
    df_left = df_example[df_example.assets <= T]
    df_right = df_example[df_example.assets > T]
    
    display(df_left)
    print(df_left.status.value_counts(normalize=True))
    display(df_right)
    print(df_right.status.value_counts(normalize=True))

    print()

0

   assets   status
2       0  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
1    2000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

2000

   assets   status
1    2000  default
2       0  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

3000

   assets   status
1    2000  default
2       0  default
7    3000  default

status
default    1.0
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok

status
ok         0.8
default    0.2
Name: proportion, dtype: float64

4000

   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok

status
ok         0.75
default    0.25
Name: proportion, dtype: float64

5000

   assets   status
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

   assets   status
0    8000  default
6    9000       ok

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

8000

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
7    3000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

   assets status
6    9000     ok

status
ok    1.0
Name: proportion, dtype: float64

In [55]:
T = 4000
df_left = df_example[df_example.assets <= T]
df_right = df_example[df_example.assets > T]

display(df_left)
print(df_left.status.value_counts(normalize=True))
display(df_right)
print(df_left.status.value_counts(normalize=True))

   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

In [56]:
results = []

for T in Ts:
    df_left = df_example[df_example.assets <= T]
    df_right = df_example[df_example.assets > T]
    
    # Calculate value proportions
    left_props = df_left.status.value_counts(normalize=True)
    right_props = df_right.status.value_counts(normalize=True)
    
    # Decisions (majority class)
    left_dec = df_left.status.mode()[0] if not df_left.empty else 'none'
    right_dec = df_right.status.mode()[0] if not df_right.empty else 'none'
    
    # Impurities (1 - max proportion)
    left_imp = 1 - left_props.max() if not left_props.empty else 0
    right_imp = 1 - right_props.max() if not right_props.empty else 0
    
    # Simple average of left and right impurities
    avg_imp = (left_imp + right_imp) / 2
    
    results.append({
        'T': T,
        'decision LEFT': left_dec,
        'impurity LEFT': f"{round(left_imp * 100)}%",
        'decision RIGHT': right_dec,
        'impurity RIGHT': f"{round(right_imp * 100)}%",
        'AVG': f"{round(avg_imp * 100)}%"
    })

df_scores = pd.DataFrame(results)
display(df_scores)

      T decision LEFT impurity LEFT decision RIGHT impurity RIGHT  AVG
0     0       default            0%             ok            43%  21%
1  2000       default            0%             ok            33%  17%
2  3000       default            0%             ok            20%  10%
3  4000       default           25%             ok            25%  25%
4  5000       default           50%        default            50%  50%
5  8000       default           43%             ok             0%  21%

In [57]:
data = [
    [8000, 3000, 'default'],
    [2000, 1000, 'default'],
    [   0, 1000, 'default'],
    [5000, 1000, 'ok'],
    [5000, 1000, 'ok'],
    [4000, 1000, 'ok'],
    [9000,  500, 'ok'],
    [3000, 2000, 'default'],
]

df_example = pd.DataFrame(data, columns=['assets', 'debt', 'status'])

In [58]:
df_example

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

In [59]:
df_example.sort_values('debt')

   assets  debt   status
6    9000   500       ok
1    2000  1000  default
3    5000  1000       ok
2       0  1000  default
5    4000  1000       ok
4    5000  1000       ok
7    3000  2000  default
0    8000  3000  default

In [60]:
thresholds = {
    'assets': [0, 2000, 3000, 4000, 5000, 8000],
    'debt': [500, 1000, 2000]
}

In [61]:
thresholds = {
    'assets': [0, 2000, 3000, 4000, 5000, 8000],
    'debt': [500, 1000, 2000]
}

for feature, Ts in thresholds.items():
    print('#####################')
    print(feature)
    for T in Ts:
        print(T)
        df_left = df_example[df_example[feature] <= T]
        df_right = df_example[df_example[feature] > T]

        display(df_left)
        print(df_left.status.value_counts(normalize=True))
        display(df_right)
        print(df_right.status.value_counts(normalize=True))

        print()
    print('#####################')

#####################
assets
0

   assets  debt   status
2       0  1000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

2000

   assets  debt   status
1    2000  1000  default
2       0  1000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

3000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
7    3000  2000  default

status
default    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok

status
ok         0.8
default    0.2
Name: proportion, dtype: float64

4000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
5    4000  1000       ok
7    3000  2000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
3    5000  1000       ok
4    5000  1000       ok
6    9000   500       ok

status
ok         0.75
default    0.25
Name: proportion, dtype: float64

5000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
6    9000   500       ok

status
default    0.5
ok         0.5
Name: proportion, dtype: float64

8000

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

   assets  debt status
6    9000   500     ok

status
ok    1.0
Name: proportion, dtype: float64

#####################
#####################
debt
500

   assets  debt status
6    9000   500     ok

status
ok    1.0
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
7    3000  2000  default

status
default    0.571429
ok         0.428571
Name: proportion, dtype: float64

1000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok

status
ok         0.666667
default    0.333333
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default
7    3000  2000  default

status
default    1.0
Name: proportion, dtype: float64

2000

   assets  debt   status
1    2000  1000  default
2       0  1000  default
3    5000  1000       ok
4    5000  1000       ok
5    4000  1000       ok
6    9000   500       ok
7    3000  2000  default

status
ok         0.571429
default    0.428571
Name: proportion, dtype: float64

   assets  debt   status
0    8000  3000  default

status
default    1.0
Name: proportion, dtype: float64

#####################

In [62]:
from IPython.display import display

thresholds = {
    'assets': [0, 2000, 3000, 4000, 5000, 8000],
    'debt': [500, 1000, 2000]
}

all_results = []

for feature, Ts in thresholds.items():
    for T in Ts:
        df_left = df_example[df_example[feature] <= T]
        df_right = df_example[df_example[feature] > T]
        
        # Proportions
        left_props = df_left.status.value_counts(normalize=True)
        right_props = df_right.status.value_counts(normalize=True)
        
        # Majority decisions
        left_dec = df_left.status.mode()[0] if not df_left.empty else 'none'
        right_dec = df_right.status.mode()[0] if not df_right.empty else 'none'
        
        # Impurities (1 - max proportion)
        left_imp = 1 - left_props.max() if not left_props.empty else 0
        right_imp = 1 - right_props.max() if not right_props.empty else 0
        
        # Average impurity
        avg_imp = (left_imp + right_imp) / 2
        
        all_results.append({
            'feature': feature,
            'T': T,
            'decision LEFT': left_dec,
            'impurity LEFT': f"{round(left_imp * 100)}%",
            'decision RIGHT': right_dec,
            'impurity RIGHT': f"{round(right_imp * 100)}%",
            'AVG': f"{round(avg_imp * 100)}%",
            '_raw_avg': avg_imp  # kept for sorting/finding best T easily
        })

# Create master DataFrame
df_scores = pd.DataFrame(all_results)

# Display full results grouped or sorted
display(df_scores.drop(columns=['_raw_avg']))

# Find and print the best T for each feature
print("\n--- Best Thresholds ---")
for feature in thresholds.keys():
    feat_df = df_scores[df_scores['feature'] == feature]
    best_row = feat_df.loc[feat_df['_raw_avg'].idxmin()]
    print(f"Feature: {feature} -> Best T = {best_row['T']} (AVG Impurity: {best_row['AVG']})")

  feature     T decision LEFT impurity LEFT decision RIGHT impurity RIGHT  AVG
0  assets     0       default            0%             ok            43%  21%
1  assets  2000       default            0%             ok            33%  17%
2  assets  3000       default            0%             ok            20%  10%
3  assets  4000       default           25%             ok            25%  25%
4  assets  5000       default           50%        default            50%  50%
5  assets  8000       default           43%             ok             0%  21%
6    debt   500            ok            0%        default            43%  21%
7    debt  1000            ok           33%        default             0%  17%
8    debt  2000            ok           43%        default             0%  21%

--- Best Thresholds ---
Feature: assets -> Best T = 3000 (AVG Impurity: 10%)
Feature: debt -> Best T = 1000 (AVG Impurity: 17%)

In [64]:
"""
The split-finding algorithm:
FOR each feature in FEATURES:
    FIND all thresholds for the feature
    FOR each threshold in thresholds:
        SPLIT the dataset using "feature > threshold" condition
        COMPUTE the impurity of this split
SELECT the condition with the LOWEST IMPURITY
"""

'\nThe split-finding algorithm:\nFOR each feature in FEATURES:\n    FIND all thresholds for the feature\n    FOR each threshold in thresholds:\n        SPLIT the dataset using "feature > threshold" condition\n        COMPUTE the impurity of this split\nSELECT the condition with the LOWEST IMPURITY\n'

In [65]:
"""
Stopping criteria
After the root is split, the algorithm applies the same procedure recursively to the left and right sides. When does it stop?

The group is already pure - the misclassification rate is 0%, no point in splitting further.
The tree reached the maximum depth limit - controlled by max_depth.
The group is too small to split - controlled by min_samples_leaf.
The maximum number of leaves (decision nodes) was reached.
These stopping criteria are what keep a tree from overfitting.
"""

'\nStopping criteria\nAfter the root is split, the algorithm applies the same procedure recursively to the left and right sides. When does it stop?\n\nThe group is already pure - the misclassification rate is 0%, no point in splitting further.\nThe tree reached the maximum depth limit - controlled by max_depth.\nThe group is too small to split - controlled by min_samples_leaf.\nThe maximum number of leaves (decision nodes) was reached.\nThese stopping criteria are what keep a tree from overfitting.\n'

In [66]:
"""
The full algorithm
Putting everything together:

Find the best split: for every feature, try all possible thresholds and pick the condition with the lowest impurity.
If the stopping criteria are not met (max depth not reached, groups large enough and not pure), repeat for the left side and the right side.
"""

'\nThe full algorithm\nPutting everything together:\n\nFind the best split: for every feature, try all possible thresholds and pick the condition with the lowest impurity.\nIf the stopping criteria are not met (max depth not reached, groups large enough and not pure), repeat for the left side and the right side.\n'